import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ThemeSwitcher from "../components/ThemeSwitcher";
import Navbar from "../components/Navbar";
import { Text, Button } from "@chakra-ui/react";
import { useState } from "react";
import { ethers } from "ethers";

function Home() {
  return (
    <div>
      <Head>
        <title>0xChange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Comforter&family=Poppins:wght@300&family=Supermercado+One&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <Text
          bgGradient="linear(to-l, #7928CA, #FF0080)"
          bgClip="text"
          fontSize="6xl"
          fontWeight="extrabold"
          className={styles.welcomeText}
        >
          Welcome to 0xChange
        </Text>
        <Text
          bgGradient="linear(to-l, #7928CA, #FF0080)"
          bgClip="text"
          fontSize="3xl"
          fontWeight="extrabold"
          className={styles.welcomeText}
        >
          a one of a kind multi-chain wallet and exchange
        </Text>
        <Text
          bgGradient="linear(to-l, #7928CA, #FF0080)"
          bgClip="text"
          fontSize="3xl"
          fontWeight="extrabold"
          className={styles.welcomeText}
        >
          get started by connecting your wallet{" "}
        </Text>
      </main>
    </div>
  );
}

export default Home;
